import type { Metadata } from "next";
import { Geist } from "next/font/google";

import "@/styles/globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ancil Labs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} flex flex-col antialiased scroll-smooth`}
      >
        <Navbar />
        <main className="grow mt-[100px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
